blank_issues_enabled: false
contact_links:
  - name: Have a suggestion?
    url: https://github.com/APickledWalrus/.github/
    about: Please share your suggestions here.
  - name: Have a question?
    url: https://github.com/APickledWalrus/.github/
    about: Please ask your questions here.
