blank_issues_enabled: false
contact_links:
  - name: Have a suggestion?
    url: https://github.com/APickledWalrus/.github/
    about: Suggestions can be shared in the Discussions tab.
  - name: Have a question?
    url: https://github.com/APickledWalrus/.github/
    about: Questions can be asked in the Discussions tab.
