blank_issues_enabled: false
contact_links:
  - name: Need help or have a question?
    url: https://github.com/APickledWalrus/.github/blob/main/SUPPORT.md
    about: Please refer to our support document.
