name: Suggestion
description: Suggest a new feature or change for the project.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please ensure that your suggestion is not already possible.
        > Additionally, ensure that your suggestion has not already been posted.
  - type: textarea
    attributes:
      label: Suggestion
      description: Enter your suggestion here. Try to be as thorough as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: Tell us why you want to see this implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives for this suggestion? Is this already possible through a different method?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: Have anything else to add?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > By submitting this suggestion, you agree to follow the standards outlined in our [Code of Conduct](https://github.com/APickledWalrus/.github/blob/main/CODE_OF_CONDUCT.md). \
        > Thank you for your suggestion.
